// GENERATED by analysis/core/table_columns.py — do not edit by hand.
// The Layer 1 table's columns, declared once for the builder, the gate and this file
// (DASHBOARD_SPEC §21.5). tests/test_table_columns.py fails when this file drifts.

/** The columns a row can carry, in the order the table draws them. */
export const COLUMNS = ["size", "of_cut", "of_book", "growth", "pace", "new", "real_credit", "output"] as const;
export type ColKey = typeof COLUMNS[number];

export const COL_LABEL: Record<ColKey, string> = {
  size: "Size",
  of_cut: "of cut",
  of_book: "of book",
  growth: "Growth",
  pace: "Pace",
  new: "New",
  real_credit: "Real credit",
  output: "Output 12m",
};

/** The header group a column sits under, or null. */
export const COL_GROUP: Record<ColKey, string | null> = {
  size: null,
  of_cut: null,
  of_book: null,
  growth: null,
  pace: null,
  new: null,
  real_credit: "real",
  output: "real",
};

export const GROUP_LABEL: Record<string, string> = {
  real: "vs the real economy",
};
