// GENERATED by analysis/core/table_columns.py — do not edit by hand.
// The Layer 1 table's columns, declared once for the builder, the gate and this file
// (DASHBOARD_SPEC §21.5). tests/test_table_columns.py fails when this file drifts.

/** The columns a row can carry, in the order the table draws them. */
export const COLUMNS = ["size", "of_cut", "of_book", "growth", "pace", "new", "real_credit", "output"] as const;
export type ColKey = typeof COLUMNS[number];

export const COL_LABEL: Record<ColKey, string> = {
  size: "Size",
  of_cut: "of cut",
  of_book: "of book",
  growth: "Growth",
  pace: "Pace",
  new: "New",
  real_credit: "Real credit",
  output: "Output 12m",
};

/** The header group a column sits under, or null. */
export const COL_GROUP: Record<ColKey, string | null> = {
  size: null,
  of_cut: null,
  of_book: null,
  growth: null,
  pace: null,
  new: null,
  real_credit: "real",
  output: "real",
};

export const GROUP_LABEL: Record<string, string> = {
  real: "vs the real economy",
};

/** What each heading means, shown on hover. */
export const COL_HINT: Record<ColKey, string> = {
  size: "How big this part is today, in the table's own unit.",
  of_cut: "Its share of this table: the parts added up.",
  of_book: "Its share of the whole book, not just of this table.",
  growth: "Year-on-year growth: now against the same month a year ago.",
  pace: "Is growth speeding up or slowing down? The change in year-on-year growth since the previous reading, in percentage points.",
  new: "Of the net change over the last 12 months, the part that came from here. Reads 'Of fall' when the total shrank; can pass 100% when parts move in opposite directions.",
  real_credit: "Growth with price changes taken out, using the prices of what this part produces. Hover a cell for the price index used.",
  output: "Growth in real output (GVA) over the last four quarters: the economy this credit funds.",
};

export const GROUP_HINT: Record<string, string> = {
  real: "Credit set against prices and output, from MoSPI's national statistics.",
};
