#!/usr/bin/env python3
"""
table_columns.py — the Layer 1 table's columns, declared once (DASHBOARD_SPEC §21.5)
───────────────────────────────────────────────────────────────────────────────────
The column list used to be typed in three places: the builder (`core/table_rows.py`), the gate
(`guards/validate_cut_table.py`) and the browser (`web/lib/table.ts`). Nothing kept them in step,
so a new column would have been built and drawn without the gate ever reading it.

Now there is one declaration. The builder and the gate import it, and the browser's constant is
GENERATED from it (`web/lib/table_columns.ts`); `tests/test_table_columns.py` fails if the
generated file is not what this module renders.

    python3 analysis/core/table_columns.py --write     # regenerate the TypeScript
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

ROOT = next(p for p in Path(__file__).resolve().parents if (p / ".git").is_dir())
TS_OUT = ROOT / "web" / "lib" / "table_columns.ts"


@dataclass(frozen=True)
class Column:
    key: str
    label: str
    kind: str              # "level" (the cut's own unit) | "pct" | "pp"
    group: str | None = None
    #: What the column means, in plain words, shown when the reader hovers its heading. It
    #: carries no number and names no pipeline, because the same heading sits on credit,
    #: payments and NBFC tables alike.
    hint: str = ""


#: In the order the table draws them.
COLUMNS: tuple[Column, ...] = (
    Column("size",        "Size",        "level",
           hint="How big this part is today, in the table's own unit."),
    Column("of_cut",      "of cut",      "pct",
           hint="Its share of this table: the parts added up."),
    Column("of_book",     "of book",     "pct",
           hint="Its share of the whole book, not just of this table."),
    Column("growth",      "Growth",      "pct",
           hint="Year-on-year growth: now against the same month a year ago."),
    Column("pace",        "Pace",        "pp",
           hint="Is growth speeding up or slowing down? The change in year-on-year growth "
                "since the previous reading, in percentage points."),
    Column("new",         "New",         "pct",
           hint="Of the net change over the last 12 months, the part that came from here. "
                "Reads 'Of fall' when the total shrank; can pass 100% when parts move in "
                "opposite directions."),
    # 1f (signals/README §1f): drawn only on a cut that declares 1f signals.
    Column("real_credit", "Real credit", "pct", "real",
           hint="Growth with price changes taken out, using the prices of what this part "
                "produces. Hover a cell for the price index used."),
    Column("output",      "Output 12m",  "pct", "real",
           hint="Growth in real output (GVA) over the last four quarters: the economy this "
                "credit funds."),
)

#: Column groups get a header above their columns.
GROUPS = {"real": "vs the real economy"}
GROUP_HINTS = {"real": "Credit set against prices and output, from MoSPI's national statistics."}

#: The 1f signal behind each 1f column, by method.
F1_COLUMN = {"csv_sector_real_growth": "real_credit", "csv_sector_output_growth": "output"}

KEYS = tuple(c.key for c in COLUMNS)


def render_ts() -> str:
    cols = ", ".join(f'"{c.key}"' for c in COLUMNS)
    labels = "\n".join(f'  {c.key}: "{c.label}",' for c in COLUMNS)
    groups = "\n".join(f'  {c.key}: {"null" if c.group is None else repr(c.group).replace(chr(39), chr(34))},'
                       for c in COLUMNS)
    glabels = "\n".join(f'  {k}: "{v}",' for k, v in GROUPS.items())
    hints = "\n".join(f'  {c.key}: "{c.hint}",' for c in COLUMNS)
    ghints = "\n".join(f'  {k}: "{v}",' for k, v in GROUP_HINTS.items())
    return f"""// GENERATED by analysis/core/table_columns.py — do not edit by hand.
// The Layer 1 table's columns, declared once for the builder, the gate and this file
// (DASHBOARD_SPEC §21.5). tests/test_table_columns.py fails when this file drifts.

/** The columns a row can carry, in the order the table draws them. */
export const COLUMNS = [{cols}] as const;
export type ColKey = typeof COLUMNS[number];

export const COL_LABEL: Record<ColKey, string> = {{
{labels}
}};

/** The header group a column sits under, or null. */
export const COL_GROUP: Record<ColKey, string | null> = {{
{groups}
}};

export const GROUP_LABEL: Record<string, string> = {{
{glabels}
}};

/** What each heading means, shown on hover. */
export const COL_HINT: Record<ColKey, string> = {{
{hints}
}};

export const GROUP_HINT: Record<string, string> = {{
{ghints}
}};
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    if args.write:
        TS_OUT.write_text(render_ts())
        print(f"  ✓ wrote {TS_OUT.relative_to(ROOT)}")
        return 0
    ok = TS_OUT.exists() and TS_OUT.read_text() == render_ts()
    print("  ✓ table columns in step" if ok else f"  ✗ {TS_OUT.relative_to(ROOT)} is stale — run with --write")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
