"""
The manifest is the single declaration of what each gate runs and what it rewrites.
Two consumers depend on that being true — core/gate.py and guards/check_derived_fresh.py —
so these tests guard the contract between them rather than either one's internals.

The regression these exist for: the freshness guard used to keep its own hand-written copy
of the artifact list, and it silently fell behind. `sibc_l1_annotations.json` and
`atm_pos_insights.json` — the two largest artifacts the gate writes — went unguarded for
months. A test that simply asserts they are declared would have caught it the day it happened.
"""
import re
import sys
from pathlib import Path

import pytest

ANALYSIS = next(p for p in Path(__file__).resolve().parents if (p / ".git").is_dir()) / "analysis"
sys.path.insert(0, str(ANALYSIS))

from core import manifest  # noqa: E402

ROOT = ANALYSIS.parent


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_manifest_loads_and_declares_a_gate(pipeline):
    man = manifest.load(pipeline)
    assert man["id"] == pipeline
    assert man["gate"], "a pipeline with no stages is not a pipeline"


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_every_stage_resolves_to_something_runnable(pipeline):
    """A stage names a core engine, a pipeline module, or a builtin — never nothing."""
    man = manifest.load(pipeline)
    vars_ = {"$ID": pipeline, "$LATEST": "2026-06-30", "$PERIOD": "merged", "$XLSX": ""}
    for key, rel in man["paths"].items():
        vars_["$" + key.upper()] = str(ROOT / rel)

    for stage in man["gate"]:
        if "builtin" in stage:
            continue
        cmd, cwd = manifest.resolve(stage, man, vars_)
        assert cmd, f"{pipeline}/{stage['id']} resolves to no command"
        script = Path(cmd[1])
        assert script.exists(), f"{pipeline}/{stage['id']} → missing script {script}"
        assert not any("$" in a for a in cmd), f"{pipeline}/{stage['id']} left a $VAR unsubstituted"


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_regenerating_stages_keep_manifest_order(pipeline):
    """Manifest order is dependency order — a skeleton before the state computed from it.
    The freshness guard replays these in sequence, so the filter must not reorder them."""
    man = manifest.load(pipeline)
    gate_order = [s["id"] for s in man["gate"]]
    regen_order = [s["id"] for s in manifest.regenerating_stages(man)]
    assert regen_order == [i for i in gate_order if i in set(regen_order)]


# The artifacts whose staleness has actually bitten, plus the two that were unguarded.
@pytest.mark.parametrize("artifact", [
    "web/public/data/sibc_l1_annotations.json",   # was unguarded — Stage 5.5 writes it
    "web/public/data/atm_pos_insights.json",      # was unguarded — Stage 4b writes it
    "web/public/data/atm_pos_signals.json",       # was unguarded — Stage 4a writes it
    "web/public/data/opportunities_feed.json",
    "web/public/data/sibc_planes.json",
    "web/public/data/atm_pos_planes.json",
    "analysis/rbi_sibc/merged/system_state_*.json",
])
def test_committed_artifact_is_declared_by_some_stage(artifact):
    assert artifact in manifest.derived_globs(), (
        f"{artifact} is regenerated by the gate but no stage declares it, so nothing "
        f"guards its freshness. Add it to that stage's `derived` list.")


def test_derived_globs_are_deduplicated():
    """Both pipelines regenerate the cross-source artifacts; the guard should watch each once."""
    globs = manifest.derived_globs()
    assert len(globs) == len(set(globs))
    assert "web/public/data/opportunities_feed.json" in globs


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_declared_artifacts_exist_on_disk(pipeline):
    """Every declared artifact should already be committed — a glob matching nothing means
    the declaration is wrong (typo, or the stage never actually ran)."""
    for stage in manifest.regenerating_stages(manifest.load(pipeline)):
        for glob in stage["derived"]:
            matches = list(ROOT.glob(glob))
            assert matches, f"{pipeline}/{stage['id']} declares {glob}, which matches no file"


def test_ingestion_stages_declare_nothing_derived():
    """Stages that need the raw XLSX cannot be replayed by the pre-commit guard, so they must
    not claim artifacts — otherwise the guard would try to regenerate them and fail."""
    man = manifest.load("atm_pos")
    for stage in man["gate"]:
        if stage.get("skip_if") == "revalidate":
            assert "derived" not in stage, (
                f"{stage['id']} needs the source file, so the freshness guard cannot replay it")


# ── Declared paths must be read, not restated ─────────────────────────────────
# The manifest has always carried `consolidated_csv`, and until 2026-08-11 six live modules
# hardcoded the same path instead — so the declaration was decorative and moving the file was a
# six-file edit. This is the test that keeps it read.

LIVE_DIRS = ("core", "signals", "pipelines", "cross", "guards", "distribution")
CSV_LITERAL = re.compile(r"[\"'][^\"'\n]*(?:rbi_sibc|atm_pos)_consolidated\.csv[\"']")


def _live_modules():
    for d in LIVE_DIRS:
        for f in (ANALYSIS / d).rglob("*.py"):
            if "__pycache__" not in str(f):
                yield f


def test_no_live_module_hardcodes_a_consolidated_csv_path():
    """Use core.manifest.consolidated_csv(pipeline). A path in two places is a path that can
    disagree with itself — and this one is the source every Layer-1 signal is computed from."""
    offenders = []
    for f in _live_modules():
        for line in f.read_text().splitlines():
            stripped = line.strip()
            if stripped.startswith("#") or '"""' in line:
                continue          # prose and docstrings may name the file
            if CSV_LITERAL.search(line) and "consolidated_csv(" not in line:
                offenders.append(f"{f.relative_to(ANALYSIS)}: {stripped[:70]}")
    assert not offenders, "hardcoded consolidated-CSV path(s):\n  " + "\n  ".join(offenders)


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_consolidated_csv_resolves_to_a_real_file(pipeline):
    csv = manifest.consolidated_csv(pipeline)
    assert csv.exists(), f"{pipeline} declares {csv}, which does not exist"
    assert csv.stat().st_size > 0


# ── Pipeline discovery ────────────────────────────────────────────────────────
# `PIPELINE_IDS` was a literal pair. The cost was never the tuple; it was that the same
# pair is spelled out in argparse choices, dict comprehensions and guard loops elsewhere,
# so a third source meant hunting for all of them. These pin the discovered contract.

def test_every_manifest_directory_is_discovered():
    """A pipeline declares itself by having a pipeline.json. Nothing else decides."""
    on_disk = {d.name for d in (ANALYSIS / "pipelines").iterdir()
               if (d / "pipeline.json").is_file()}
    assert set(manifest.PIPELINE_IDS) == on_disk


def test_discovery_order_is_declared_not_alphabetical():
    """Order decides the sequence check_derived_fresh replays stages in, and both pipelines
    write the shared opportunities_feed.json — so name-sorting would reorder who writes last.

    Asserted as a property rather than by pinning today's pair: a third pipeline must not
    make this test fail, only a pipeline that stops declaring its order."""
    ids = manifest.PIPELINE_IDS
    orders = [manifest.load(p).get("order") for p in ids]
    declared = [o for o in orders if o is not None]
    assert declared == sorted(declared), f"declared order not honoured: {list(zip(ids, orders))}"
    # Undeclared ones sort last, never interleaved among the declared.
    assert orders == sorted(orders, key=lambda o: (o is None, o or 0))


def test_a_new_pipeline_directory_would_be_picked_up(tmp_path, monkeypatch):
    """The point of discovery: adding a source must not require editing this module.

    Driven synthetically — asserting against the live pair would only re-state what
    test_every_manifest_directory_is_discovered already checks, and would pass for a
    hardcoded list too.

    The names deliberately CONTRADICT their declared order (`beta` is 1, `alpha` is 2), so
    this also fails an implementation that sorts by name. The first version of this fixture
    used alphabetical names and passed against a deliberately broken discovery — a test that
    asserts nothing looks exactly like a test that passes."""
    pipelines = tmp_path / "pipelines"
    for name, order in (("alpha", 2), ("beta", 1), ("zeta", None)):
        d = pipelines / name
        d.mkdir(parents=True)
        body = {"id": name} if order is None else {"id": name, "order": order}
        (d / "pipeline.json").write_text(__import__("json").dumps(body))
    (pipelines / "not_a_pipeline").mkdir()          # no manifest → not a pipeline
    monkeypatch.setattr(manifest, "ANALYSIS", tmp_path)
    assert manifest.discover_pipeline_ids() == ("beta", "alpha", "zeta")


#: Modules allowed to name both pipelines literally, each for a stated reason. An exemption
#: is a decision on the record, not a hole: anything not listed here must derive its
#: population. Delete an entry when its reason stops holding.
PAIR_EXEMPT = {
    # Not "all pipelines" — the credit half and the payments half of the merged Substack
    # issue. `data_vintage` is guarded by `len(out) == 2` and `vintage_sentence` reads both
    # by name, so a third source must NOT silently join that sentence.
    "distribution/distribution_sources.py",
    # Iterates compute MODULES, not pipelines. Becomes manifest-driven when the compute path
    # is schema-declared (ARCHITECTURE.md "Adding a pipeline", item 2).
    "architecture/reconcile.py",
}


def _docstring_lines(src: str) -> set[int]:
    """Line numbers occupied by docstrings, so prose is not read as code.

    Written after the first version of the pair check flagged a docstring that QUOTES the
    literal it exists to ban. A `startswith('\"\"\"')` test only sees the opening line of a
    multi-line docstring — so the choice was to weaken the check or to teach it the
    difference. Prose explaining a rule should never be able to violate it.
    """
    import ast
    lines: set[int] = set()
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return lines
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        body = getattr(node, "body", None)
        if body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant) \
                and isinstance(body[0].value.value, str):
            d = body[0]
            lines.update(range(d.lineno, (d.end_lineno or d.lineno) + 1))
    return lines


PAIR_LITERAL = re.compile(r'''["']sibc["']\s*,\s*["']atm_pos["']|["']atm_pos["']\s*,\s*["']sibc["']''')


def test_no_live_module_hardcodes_the_pipeline_pair():
    """Use manifest.PIPELINE_IDS, or manifest.pipelines_with_stage() for artifact populations.

    The literal pair was never the expense; finding all of its spellings was. It sat in
    argparse choices, sidecar dict comprehensions and guard loops — and in test loops, which
    is worse, because a test whose population is a hardcoded pair stops covering the next
    source without ever going red. That is how a reachability check scoped to SIBC let three
    payments anchor tables ship to no surface at all.
    """
    offenders = []
    for f in _live_modules():
        rel = str(f.relative_to(ANALYSIS))
        if rel in PAIR_EXEMPT:
            continue
        src = f.read_text()
        prose = _docstring_lines(src)      # AST, not a startswith guess — see the helper
        for n, line in enumerate(src.splitlines(), 1):
            stripped = line.strip()
            if n in prose or stripped.startswith("#") or "PAIR_EXEMPT" in line:
                continue
            if PAIR_LITERAL.search(line):
                offenders.append(f"{rel}:{n}: {stripped[:70]}")
    assert not offenders, (
        "pipeline pair hardcoded — derive it instead:\n  " + "\n  ".join(offenders))


# ── The declared compute path ─────────────────────────────────────────────────
# A pipeline declares the SHAPE of its source (`compute_module`) rather than the engine
# branching on its id. `csv_sector` is "one measure over a code hierarchy" — not "SIBC" —
# which is why a third source of that shape needs no copied module.

@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_every_pipeline_declares_a_resolvable_compute_module(pipeline):
    from signals.compute import engine
    assert engine.module_for(pipeline) is not None


def test_an_undeclared_compute_module_raises_rather_than_computing_nothing(monkeypatch):
    """Silence is the wrong answer to a shape the engine cannot resolve — it looks exactly
    like a source that simply has no signals yet. The engine already refuses an unknown
    METHOD name for this reason; an unknown module is the same failure one level up."""
    from signals.compute import engine
    monkeypatch.setattr(manifest, "load", lambda p: {"id": p})              # no compute_module
    with pytest.raises(KeyError, match="compute_module"):
        engine.module_for("whatever")
    monkeypatch.setattr(manifest, "load", lambda p: {"compute_module": "not_a_shape"})
    with pytest.raises(KeyError, match="not_a_shape"):
        engine.module_for("whatever")


def test_a_schema_declaration_the_csv_does_not_honour_raises(tmp_path, monkeypatch):
    """The manifest's `schema` block must be load-bearing, not decoration.

    `consolidated_csv` was declared by every manifest and read by almost nobody for months,
    which is how the same path came to be hardcoded in nine modules. A declaration that
    nothing verifies decays the same way, so loading the frame checks it."""
    from signals.compute import csv_sector
    csv = tmp_path / "x.csv"
    csv.write_text("date,code,parent_code,level,sector,outstanding_cr\n"
                   "2026-07-31,1,,1,Agriculture,100.0\n")
    monkeypatch.setattr(manifest, "consolidated_csv", lambda p: csv)
    monkeypatch.setattr(csv_sector.manifest, "consolidated_csv", lambda p: csv)

    # Declares a scope column the file does not have.
    monkeypatch.setattr(csv_sector.manifest, "load",
                        lambda p: {"schema": {"scope_column": "statement"}})
    csv_sector.invalidate_cache()
    with pytest.raises(ValueError, match="scope_column"):
        csv_sector._load_df("ghost")

    # Declares nothing beyond the required columns → loads, with no scope and no memo lens.
    monkeypatch.setattr(csv_sector.manifest, "load", lambda p: {"schema": {}})
    csv_sector.invalidate_cache()
    df = csv_sector._load_df("ghost")
    assert csv_sector._val(df, "2026-07-31", "1") == 100.0, \
        "a source with no scope column must still resolve a plain code"
    assert csv_sector._scope({}, df) is None
    csv_sector.invalidate_cache()


def test_a_source_missing_a_required_column_raises(tmp_path, monkeypatch):
    from signals.compute import csv_sector
    csv = tmp_path / "y.csv"
    csv.write_text("date,code,level,sector,outstanding_cr\n2026-07-31,1,1,Agriculture,100.0\n")
    monkeypatch.setattr(csv_sector.manifest, "consolidated_csv", lambda p: csv)
    monkeypatch.setattr(csv_sector.manifest, "load", lambda p: {"schema": {}})
    csv_sector.invalidate_cache()
    with pytest.raises(ValueError, match="parent_code"):
        csv_sector._load_df("ghost")
    csv_sector.invalidate_cache()
