"""
The manifest is the single declaration of what each gate runs and what it rewrites.
Two consumers depend on that being true — core/gate.py and guards/check_derived_fresh.py —
so these tests guard the contract between them rather than either one's internals.

The regression these exist for: the freshness guard used to keep its own hand-written copy
of the artifact list, and it silently fell behind. `sibc_l1_annotations.json` and
`atm_pos_insights.json` — the two largest artifacts the gate writes — went unguarded for
months. A test that simply asserts they are declared would have caught it the day it happened.
"""
import re
import sys
from pathlib import Path

import pytest

ANALYSIS = next(p for p in Path(__file__).resolve().parents if (p / ".git").is_dir()) / "analysis"
sys.path.insert(0, str(ANALYSIS))

from core import manifest  # noqa: E402

ROOT = ANALYSIS.parent


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_manifest_loads_and_declares_a_gate(pipeline):
    man = manifest.load(pipeline)
    assert man["id"] == pipeline
    assert man["gate"], "a pipeline with no stages is not a pipeline"


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_every_stage_resolves_to_something_runnable(pipeline):
    """A stage names a core engine, a pipeline module, or a builtin — never nothing."""
    man = manifest.load(pipeline)
    vars_ = {"$ID": pipeline, "$LATEST": "2026-06-30", "$PERIOD": "merged", "$XLSX": ""}
    for key, rel in man["paths"].items():
        vars_["$" + key.upper()] = str(ROOT / rel)

    for stage in man["gate"]:
        if "builtin" in stage:
            continue
        cmd, cwd = manifest.resolve(stage, man, vars_)
        assert cmd, f"{pipeline}/{stage['id']} resolves to no command"
        script = Path(cmd[1])
        assert script.exists(), f"{pipeline}/{stage['id']} → missing script {script}"
        assert not any("$" in a for a in cmd), f"{pipeline}/{stage['id']} left a $VAR unsubstituted"


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_regenerating_stages_keep_manifest_order(pipeline):
    """Manifest order is dependency order — a skeleton before the state computed from it.
    The freshness guard replays these in sequence, so the filter must not reorder them."""
    man = manifest.load(pipeline)
    gate_order = [s["id"] for s in man["gate"]]
    regen_order = [s["id"] for s in manifest.regenerating_stages(man)]
    assert regen_order == [i for i in gate_order if i in set(regen_order)]


# The artifacts whose staleness has actually bitten, plus the two that were unguarded.
@pytest.mark.parametrize("artifact", [
    "web/public/data/sibc_l1_annotations.json",   # was unguarded — Stage 5.5 writes it
    "web/public/data/atm_pos_insights.json",      # was unguarded — Stage 4b writes it
    "web/public/data/atm_pos_signals.json",       # was unguarded — Stage 4a writes it
    "web/public/data/opportunities_feed.json",
    "web/public/data/sibc_planes.json",
    "web/public/data/atm_pos_planes.json",
    "analysis/rbi_sibc/merged/system_state_*.json",
])
def test_committed_artifact_is_declared_by_some_stage(artifact):
    assert artifact in manifest.derived_globs(), (
        f"{artifact} is regenerated by the gate but no stage declares it, so nothing "
        f"guards its freshness. Add it to that stage's `derived` list.")


def test_derived_globs_are_deduplicated():
    """Both pipelines regenerate the cross-source artifacts; the guard should watch each once."""
    globs = manifest.derived_globs()
    assert len(globs) == len(set(globs))
    assert "web/public/data/opportunities_feed.json" in globs


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_declared_artifacts_exist_on_disk(pipeline):
    """Every declared artifact should already be committed — a glob matching nothing means
    the declaration is wrong (typo, or the stage never actually ran)."""
    for stage in manifest.regenerating_stages(manifest.load(pipeline)):
        for glob in stage["derived"]:
            matches = list(ROOT.glob(glob))
            assert matches, f"{pipeline}/{stage['id']} declares {glob}, which matches no file"


def test_ingestion_stages_declare_nothing_derived():
    """Stages that need the raw XLSX cannot be replayed by the pre-commit guard, so they must
    not claim artifacts — otherwise the guard would try to regenerate them and fail."""
    man = manifest.load("atm_pos")
    for stage in man["gate"]:
        if stage.get("skip_if") == "revalidate":
            assert "derived" not in stage, (
                f"{stage['id']} needs the source file, so the freshness guard cannot replay it")


# ── Declared paths must be read, not restated ─────────────────────────────────
# The manifest has always carried `consolidated_csv`, and until 2026-08-11 six live modules
# hardcoded the same path instead — so the declaration was decorative and moving the file was a
# six-file edit. This is the test that keeps it read.

LIVE_DIRS = ("core", "signals", "pipelines", "cross", "guards", "distribution")
CSV_LITERAL = re.compile(r"[\"'][^\"'\n]*(?:rbi_sibc|atm_pos)_consolidated\.csv[\"']")


def _live_modules():
    for d in LIVE_DIRS:
        for f in (ANALYSIS / d).rglob("*.py"):
            if "__pycache__" not in str(f):
                yield f


def test_no_live_module_hardcodes_a_consolidated_csv_path():
    """Use core.manifest.consolidated_csv(pipeline). A path in two places is a path that can
    disagree with itself — and this one is the source every Layer-1 signal is computed from."""
    offenders = []
    for f in _live_modules():
        for line in f.read_text().splitlines():
            stripped = line.strip()
            if stripped.startswith("#") or '"""' in line:
                continue          # prose and docstrings may name the file
            if CSV_LITERAL.search(line) and "consolidated_csv(" not in line:
                offenders.append(f"{f.relative_to(ANALYSIS)}: {stripped[:70]}")
    assert not offenders, "hardcoded consolidated-CSV path(s):\n  " + "\n  ".join(offenders)


@pytest.mark.parametrize("pipeline", manifest.PIPELINE_IDS)
def test_consolidated_csv_resolves_to_a_real_file(pipeline):
    csv = manifest.consolidated_csv(pipeline)
    assert csv.exists(), f"{pipeline} declares {csv}, which does not exist"
    assert csv.stat().st_size > 0
