#!/usr/bin/env python3
"""
Stage 4a-series — precompute compact chart series (compute-once, ship-compact).

The web dashboards must NOT download the raw consolidated CSV and re-derive series
in the browser (the ATM/POS CSV is ~4.6 MB / 47k rows — parsing + per-bank
filtering on the client is the /payments latency). This emits a compact,
numbers-only JSON the chart layer reads with plain JSON.parse and O(1) lookups.

Generic + pipeline-agnostic by design (scales to N ingestion types): a pipeline
declares its CSV path, date column, entity column, and category column; the
script precomputes, per metric, the Total series + per-entity series over all
periods. No metric list is hard-coded — every metric present in the CSV is
included, so new metrics need no code change.

Output: web/public/data/{pipeline}_chart_series.json

Usage:
    python3 analysis/generate_chart_series.py --pipeline atm_pos
"""

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import sys
sys.path.insert(0, str(next(p for p in Path(__file__).resolve().parents if (p / ".git").is_dir()) / "analysis"))
from core.paths import ROOT

# Per-pipeline column mapping — the only authored input. Add a pipeline here to
# onboard it; no other code changes.
PIPELINES = {
    "atm_pos": {
        "csv":      ROOT / "web/public/data/atm_pos_consolidated.csv",
        "out":      ROOT / "web/public/data/atm_pos_chart_series.json",
        "date_col": "report_date",
        "entity_col":   "bank_name",
        "category_col": "bank_category",
        "record_col":   "record_type",   # 'total' (aggregate) vs 'bank' (entity)
        "total_record": "total",
        "entity_record": "bank",
    },
}


def build(cfg: dict) -> dict:
    with open(cfg["csv"]) as f:
        rows = list(csv.DictReader(f))

    dcol, ecol, ccol = cfg["date_col"], cfg["entity_col"], cfg["category_col"]
    rcol = cfg["record_col"]

    periods = sorted({r[dcol] for r in rows})
    p_index = {p: i for i, p in enumerate(periods)}

    # entity (bank) roster + category — only from entity records
    cat_of: dict[str, str] = {}
    for r in rows:
        if r[rcol] == cfg["entity_record"]:
            cat_of.setdefault(r[ecol], r.get(ccol) or "")
    entities = sorted(cat_of)
    e_index = {e: i for i, e in enumerate(entities)}

    metrics = sorted({r["metric"] for r in rows})

    # series[metric] = {"total": [..periods], "entity": [[..periods] per entity]}
    def zeros():
        return [0.0] * len(periods)

    series: dict[str, dict] = {
        m: {"total": zeros(), "entity": [zeros() for _ in entities]}
        for m in metrics
    }

    for r in rows:
        m = r["metric"]
        pi = p_index.get(r[dcol])
        if pi is None:
            continue
        try:
            v = float(r["value"]) if r["value"] not in ("", None) else 0.0
        except (ValueError, TypeError):
            v = 0.0
        if r[rcol] == cfg["total_record"]:
            series[m]["total"][pi] += v
        elif r[rcol] == cfg["entity_record"]:
            ei = e_index.get(r[ecol])
            if ei is not None:
                series[m]["entity"][ei][pi] += v

    # round to keep the file compact (4 sig figs is plenty for charts)
    def rnd(x):
        return round(x, 2)
    for m in series:
        series[m]["total"] = [rnd(x) for x in series[m]["total"]]
        series[m]["entity"] = [[rnd(x) for x in row] for row in series[m]["entity"]]

    return {
        "_meta": {
            "pipeline": cfg["_pipeline"],
            "periods": periods,
            "entity_count": len(entities),
            "metric_count": len(metrics),
            "note": "Precomputed compact chart series — Total + per-entity per metric. "
                    "Replaces client-side CSV parsing. Generated by generate_chart_series.py.",
        },
        "entities": [{"name": e, "category": cat_of[e]} for e in entities],
        "series": series,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pipeline", required=True, choices=sorted(PIPELINES))
    a = ap.parse_args()
    cfg = dict(PIPELINES[a.pipeline]); cfg["_pipeline"] = a.pipeline
    out = build(cfg)
    cfg["out"].parent.mkdir(parents=True, exist_ok=True)
    with open(cfg["out"], "w") as f:
        json.dump(out, f, separators=(",", ":"))   # compact, no whitespace
    size_kb = cfg["out"].stat().st_size / 1024
    print(f"✓ {a.pipeline}: {len(out['series'])} metrics × "
          f"{out['_meta']['entity_count']} entities × {len(out['_meta']['periods'])} periods "
          f"→ {cfg['out'].name} ({size_kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
